
{'date': 'Tue Aug 28 2018 18:52:20.764 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 10
    mapa = Cena(img=MAPA)
NameError: name 'Cena' is not defined
'''},
{'date': 'Tue Aug 28 2018 18:52:43.766 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 11
    INVENTARIO.mapa.vai
AttributeError: 'Inventario' object has no attribute 'mapa'
'''},
{'date': 'Tue Aug 28 2018 18:54:10.396 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 11
    INVENTARIO.mapa.vai
AttributeError: 'Inventario' object has no attribute 'mapa'
'''},
{'date': 'Tue Aug 28 2018 18:57:01.870 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 11
    mapa(INVENTARIO)
TypeError: __call__() takes 1 positional argument but more were given
'''},
{'date': 'Tue Aug 28 2018 18:59:02.118 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  mapa = Elemento(img=MAPA,tit "Mapa"style=dict(left=50, top=160, width=200, height=200))
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 19:00:02.430 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  mapa = Elemento(img=MAPA,tit "Mapa",style=dict(left=50, top=160, width=200, height=200))
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 19:00:34.508 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  mapa = Elemento(img=MAPA,tit "Mapa",style=dict(left=50, top=160, width=200, height=200))
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 19:01:11.124 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 15
    inventario()
  module <module> line 12
    INVENTARIO.bota.elemento
AttributeError: 'method' object has no attribute 'elemento'
'''},
{'date': 'Tue Aug 28 2018 20:17:43.112 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 58
  for x, tit in enumerate(SALAS)]
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 20:18:47.348 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 59
  for x, tit in enumerate(SALAS)]
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 20:24:16.443 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 60
  for x, tit in enumerate(SALAS)]
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 20:25:04.715 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 59
  marcadores= [Elemento (img= SALAS, tit=tit, style=dict(
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Aug 28 2018 20:25:18.181 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 59
  marcadores= [Elemento (img= SALAS, tit=tit, style=dict(
                                                                                                                                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 20:25:39.423 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 59
  marcadores= [Cena (img= SALAS, tit=tit, style=dict(
                                                                                                                                            ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 20:26:00.667 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 60
  for x, tit in enumerate(SALAS)]
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 20:27:09.656 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 72
    inventario()
  module <module> line 58
    sala.vai = csala.vai  
NameError: name 'sala' is not defined
'''},
{'date': 'Tue Aug 28 2018 20:35:57.28 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 75
    inventario()
  module <module> line 61
    sala.vai = csala.vai  
NameError: name 'sala' is not defined
'''},
{'date': 'Tue Aug 28 2018 20:36:22.101 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 60
  """ csalas= Cena(img= SALAS)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Aug 28 2018 20:36:44.424 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 75
  r_oeste.vai()
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Aug 28 2018 20:39:33.417 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
Exception: x is undefined
  module '$exec_2035' line 68
inventario()
'''},
{'date': 'Tue Aug 28 2018 20:40:50.156 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 68
    inventario()
  module <module> line 58
    marcador.vai= cenas[x].vai
IndexError: list index out of range
'''},