
{'date': 'Tue Aug 28 2018 18:52:20.764 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 10
    mapa = Cena(img=MAPA)
NameError: name 'Cena' is not defined
'''},
{'date': 'Tue Aug 28 2018 18:52:43.766 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 11
    INVENTARIO.mapa.vai
AttributeError: 'Inventario' object has no attribute 'mapa'
'''},
{'date': 'Tue Aug 28 2018 18:54:10.396 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 11
    INVENTARIO.mapa.vai
AttributeError: 'Inventario' object has no attribute 'mapa'
'''},
{'date': 'Tue Aug 28 2018 18:57:01.870 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    inventario()
  module <module> line 11
    mapa(INVENTARIO)
TypeError: __call__() takes 1 positional argument but more were given
'''},
{'date': 'Tue Aug 28 2018 18:59:02.118 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  mapa = Elemento(img=MAPA,tit "Mapa"style=dict(left=50, top=160, width=200, height=200))
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Tue Aug 28 2018 19:00:02.430 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  mapa = Elemento(img=MAPA,tit "Mapa",style=dict(left=50, top=160, width=200, height=200))
                                ^
SyntaxError: invalid syntax
'''},