
{'date': 'Sun Aug 12 2018 23:26:36.664 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    from _spy.vitollino.main import inventario as inv
ImportError: cannot import name 'inventario'

ImportError
Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 264
    action()
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 3
    from _spy.vitollino.main import inventario as inv
'''},
{'date': 'Sun Aug 12 2018 23:28:44.173 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 147
    Bloco(FLORESTA)
  module <module> line 119
    Suporte(self, "folha" + fl, pos//4, pos%4)
NameError: name 'Suporte' is not defined
'''},
{'date': 'Mon Aug 13 2018 09:10:07.948 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 133
    Bloco(FLORESTA)
  module <module> line 119
    Suporte(self, "folha" + fl, pos//4, pos%4)
NameError: name 'Suporte' is not defined
'''},
{'date': 'Mon Aug 13 2018 09:10:25.792 GMt-0300 (Hora oficial do Brasil) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 133
    Bloco(FLORESTA)
  module <module> line 119
    Suporte(self, "folha" + fl, pos//4, pos%4)
NameError: name 'Suporte' is not defined
'''},
{'date': 'Mon Aug 13 2018 13:32:40.819 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 134
    Bloco(FLORESTA)
  module <module> line 122
    Folha(self, pos//4, pos%4, int(tx)//4, int(tx)%4)
  module <module> line 38
    self.folha.onmouseover = self.mouse_over
AttributeError: 'Folha' object has no attribute 'mouse_over'
'''},
{'date': 'Mon Aug 13 2018 13:37:14.148 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 133
    Bloco(FLORESTA)
  module <module> line 121
    Folha(self, pos//4, pos%4, int(tx)//4, int(tx)%4)
  module <module> line 37
    self.folha.onmouseover = self.mouse_over
AttributeError: 'Folha' object has no attribute 'mouse_over'
'''},
{'date': 'Mon Aug 13 2018 13:37:27.62 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 133
    Bloco(FLORESTA)
  module <module> line 121
    Folha(self, pos//4, pos%4, int(tx)//4, int(tx)%4)
  module <module> line 37
    self.folha.onmouseover = self.mouse_over
AttributeError: 'Folha' object has no attribute 'mouse_over'
'''},
{'date': 'Mon Aug 13 2018 15:04:37.952 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 12
    gogh = Cena(GOGH)
NameError: name 'GOGH' is not defined
'''},
{'date': 'Mon Aug 13 2018 15:04:46.460 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 141
    Bloco(FLORESTA)
  module <module> line 129
    Folha(self, pos//4, pos%4, int(tx)//4, int(tx)%4)
  module <module> line 45
    self.folha.onmouseover = self.mouse_over
AttributeError: 'Folha' object has no attribute 'mouse_over'
'''},
{'date': 'Mon Aug 13 2018 15:04:52.26 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 141
    Bloco(FLORESTA)
  module <module> line 129
    Folha(self, pos//4, pos%4, int(tx)//4, int(tx)%4)
  module <module> line 45
    self.folha.onmouseover = self.mouse_over
AttributeError: 'Folha' object has no attribute 'mouse_over'
'''},
{'date': 'Mon Aug 13 2018 16:27:18.524 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 10
  Um objeto de interação que é representado por uma imagem em uma cena.
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Aug 13 2018 16:27:37.940 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 240
    trigonometria().norte.vai()
  module <module> line 226
    vdgball = Elemento(ball, tit = "microscope", drag=True,
TypeError: 'module' object is not callable
'''},
{'date': 'Mon Aug 13 2018 18:07:11.727 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    trigonometria().norte.vai()
  module <module> line 62
    vdgball = Elemento(ball, tit = "microscope", drag=True,
TypeError: 'module' object is not callable
'''},
{'date': 'Mon Aug 13 2018 18:09:53.724 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    trigonometria().norte.vai()
  module <module> line 62
    vdgball = Elemento(ball, tit = "microscope", drag=True,
TypeError: 'module' object is not callable
'''},
{'date': 'Mon Aug 13 2018 18:11:53.466 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    trigonometria().norte.vai()
  module <module> line 62
    vdgball = Elemento(ball, tit = "microscope", drag=True,
TypeError: 'module' object is not callable
'''},
{'date': 'Mon Aug 13 2018 18:12:21.96 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 76
    trigonometria().norte.vai()
  module <module> line 62
    vdgball = Elemento(ball, tit = "microscope", drag=True,
TypeError: 'module' object is not callable
'''},
{'date': 'Mon Aug 13 2018 18:51:44.773 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 5
  from amanda.main import Elementofrom _spy.vitollino.main import STYLE, INVENTARIO, Sala, Texto, Cena
                                           ^
SyntaxError: trailing comma not allowed without surrounding parentheses
'''},
{'date': 'Mon Aug 13 2018 18:52:03.587 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 161
  colmeia = Cena(COLMEIA, nome "colmeia")
                                ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 13 2018 18:52:19.733 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 161
  colmeia = Cena(img=COLMEIA, nome "colmeia")
                                    ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Aug 13 2018 18:54:09.692 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 14
    class Elemento(Element):
  module <module> line 17
    def __init__(self, img="", vai=None, style=NDCT, tit="", alt="",
NameError: name 'NDCT' is not defined
'''},
{'date': 'Mon Aug 13 2018 18:54:44.709 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 16
    class Elemento(Element):
  module <module> line 19
    def __init__(self, img="", vai=None, style=NDCT, tit="", alt="",
NameError: name 'INVENTARIO' is not defined
'''},
{'date': 'Mon Aug 13 2018 18:55:33.668 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 174
    INVENTARIO.inicia()
NameError: name 'INVENTARIO' is not defined
'''},
{'date': 'Mon Aug 13 2018 18:55:42.9 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 175
    natureza.vai()
AttributeError: 'function' object has no attribute 'vai'
'''},
{'date': 'Mon Aug 13 2018 18:56:05.701 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 176
    natureza.vai()
AttributeError: 'function' object has no attribute 'vai'
'''},
{'date': 'Mon Aug 13 2018 18:56:22.21 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 176
    natureza.inicia()
AttributeError: 'function' object has no attribute 'inicia'
'''},