
{'date': 'Wed Aug 15 2018 12:03:53.198 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 256
    Museu()
  module <module> line 252
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
ValueError: need more than 2 values to unpack
'''},
{'date': 'Wed Aug 15 2018 12:26:07.285 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 191
  [sala_1.norte ,"Hello",  "if True:print('ooi')"],
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Aug 15 2018 13:17:11.738 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 190
  [sala_1.norte ,"Hello",  "if True:print('ooi')"],
  ^
IndentationError: unexpected indent
'''},
{'date': 'Wed Aug 15 2018 13:19:29.99 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 260
    Museu()
  module <module> line 256
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
TypeError: 'Cena' object is not iterable
'''},
{'date': 'Wed Aug 15 2018 13:19:56.409 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 260
    Museu()
  module <module> line 256
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
TypeError: 'Cena' object is not iterable
'''},